default: &default
    adapter: postgresql
    encoding: unicode

    host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
    port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
    username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") { nil } %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB") { "book_review_development" } %>

test:
    <<: *default
    database: book_review_test
#
production:
    primary: &primary_production
        <<: *default
        database: <%= ENV["POSTGRES_DB"] %>
        username: <%= ENV["POSTGRES_USER"] %>
        password: <%= ENV["POSTGRES_PASSWORD"] %>
    cache:
        <<: *primary_production
        database: book_review_api_production_cache
        migrations_paths: db/cache_migrate
    queue:
        <<: *primary_production
        database: book_review_api_production_queue
        migrations_paths: db/queue_migrate
    cable:
        <<: *primary_production
        database: book_review_api_production_cable
        migrations_paths: db/cable_migrate
